export const MBTITypeArray = [
  { mbti: "ISTJ", color: "#4298B4" },
  { mbti: "ISFJ", color: "#4298B4" },
  { mbti: "INFJ", color: "#33A474" },
  { mbti: "INTJ", color: "#B3889D" },
  { mbti: "ISTP", color: "#E4AE3A" },
  { mbti: "ISFP", color: "#E4AE3A" },
  { mbti: "INFP", color: "#33A474" },
  { mbti: "INTP", color: "#B3889D" },
  { mbti: "ESTP", color: "#E4AE3A" },
  { mbti: "ESFP", color: "#E4AE3A" },
  { mbti: "ENFP", color: "#33A474" },
  { mbti: "ENTP", color: "#B3889D" },
  { mbti: "ESTJ", color: "#4298B4" },
  { mbti: "ESFJ", color: "#4298B4" },
  { mbti: "ENFJ", color: "#33A474" },
  { mbti: "ENTJ", color: "#B3889D" },
];
